index:
        path: /
        controller: App\Controller\ImageScraperController::index

scrape:
        path: /scrape
        controller: App\Controller\ImageScraperController::scrape
        methods: POST

